6 add firingsolution and firingsolutionmanager
4322/New_2024_Robot pull request #10
Opened 2024-03-26 17:25 UTC by zaydkhan4322

please actually review this - even though it's mostly ported from the last codebase I did change it to not be a singleton

2024-03-30 23:08 UTC, dKarangula approved these changes

2024-03-30 23:09 UTC, dKarangula requested changes
Add static factory method for Firing Solution Manager

2024-03-31 00:16 UTC, Neilk1021 requested changes
The manager probably shouldn't have a generic constructor I also recommend a static factory.

2024-03-31 00:58 UTC, Neilk1021 requested changes
Change method names to explicitly say you're creating a new FiringSolutionManager. Have the factory methods have consistent names e.g. all should have createNew...

2024-03-31 01:07 UTC, Neilk1021 approved these changes

2024-03-31 01:14 UTC, dKarangula approved these changes

2024-03-31 01:16 UTC, merged